### PR TITLE
fixed cursor issue

### PR DESCRIPTION
**Pull request by mulchbutler**

### CODE REVIEW

**Review by zachmares — COMMENTED** [review]
Was part of the issue the previous lack of cur.close()?

**Comment by mulchbutler** [comment]
Yep. My assumption was to open a single cursor and use it forever, but it looks like it auto closed and the bot is broken. This change opens a new cursor for every transaction.

**Comment by zachmares** [comment]
Nice. Leeroy Jenkins!

**Review by zachmares — COMMENTED** [review]
🖱

**Review by zachmares — APPROVED** [review]

**Review by zachmares — APPROVED** [review]
Leeroy Jenkins!

**Pull request merged**
